theme: jekyll-theme-minimal
title: JJ1BBY blog
description: a Ham contester's blog
logo: /logo.png
image: /logo.png
show_downloads: false
gems:
 - jekyll-seo-tag
 - jemoji
 - jekyll-sitemap
google_analytics: UA-189717722-1
twitter:
  username: JJ1BBY
  card: summary
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /logo.png
