minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
theme: jekyll-theme-minimal
title: JJ1BBY blog
description: a Ham contester's blog
logo: /logo.png
image: /logo.png
show_downloads: false
encoding: UTF-8
gems:
 - jekyll-seo-tag
 - jemoji
 - jekyll-sitemap
 description: <meta itemprop="description" name="description" content="{% if page.description %}{{ page.description | truncate: 160 }}{% else %}{{ site.description | truncate: 160  }}{% endif %}" />
google_analytics: UA-189717722-1
twitter:
  username: JJ1BBY
  card: summary
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /logo.png
