theme: jekyll-theme-minimal
title: JJ1BBY blog
description: a Ham contester's blog
logo: ![dNbD5fWQ_400x400](https://user-images.githubusercontent.com/79028771/107864923-ce506800-6ea4-11eb-95bb-cf8bd3e3465a.jpg)
show_downloads: false
