theme: jekyll-theme-minimal
title: JJ1BBY's blog
description: a Ham contester blog
logo: [](https://user-images.githubusercontent.com/79028771/107864923-ce506800-6ea4-11eb-95bb-cf8bd3e3465a.jpg)
show_downloads: false
